
#include "token.h"

// A stringified list of the token_t type
// This is useful for printing out the name of the tokens when debugging
char* token_strings[] = {
     "TOKEN_ERROR",
     "TOKEN_EOF",
     "TOKEN_ARRAY",
     "TOKEN_BOOLEAN",
     "TOKEN_CHAR",
     "TOKEN_ELSE",
     "TOKEN_FALSE",
     "TOKEN_FOR",
     "TOKEN_FUNCTION",
     "TOKEN_IF",
     "TOKEN_INTEGER",
     "TOKEN_PRINT",
     "TOKEN_RETURN",
     "TOKEN_STRING",
     "TOKEN_TRUE",
     "TOKEN_VOID",
     "TOKEN_WHILE",
     "TOKEN_COLON",
     "TOKEN_SEMICOLON",
     "TOKEN_COMMA",
     "TOKEN_LEFTSQUAREBRACKET",
     "TOKEN_RIGHTSQUAREBRACKET",
     "TOKEN_LEFTCURLYBRACE",
     "TOKEN_RIGHTCURLYBRACE",
     "TOKEN_LEFTPAREN",
     "TOKEN_RIGHTPAREN",
     "TOKEN_EQUALS",
     "TOKEN_CARRET",
     "TOKEN_PLUS",
     "TOKEN_MINUS",
     "TOKEN_PLUSPLUS",
     "TOKEN_MINUSMINUS",
     "TOKEN_MULTIPLY",
     "TOKEN_DIVIDE",
     "TOKEN_MODULO",
     "TOKEN_EQUALSEQUALS",
     "TOKEN_GREATERTHANEQUALTO",
     "TOKEN_LESSTHANEQUALTO",
     "TOKEN_LESSTHAN",
     "TOKEN_GREATERTHAN",
     "TOKEN_NOTEQUAL",
     "TOKEN_IDENTIFIER",
     "TOKEN_NUMBER"
};
